# Alembic Configuration File for QTKĐ RAG

[alembic]
# path to migration scripts
script_location = db/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(create_date)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field if truncating of the filename is enabled
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# If set to true, sqlalchemy urls will be escaped before being
# passed to the various engines
# sqlalchemy_track_modifications = false

# logging configuration
# Defaults to empty string.
# Syntax: %(logging_qualname)s|level

sqlalchemy.url = driver://user:password@localhost/dbname


[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
