"""Freeze source passages and independent numeric UC oracles before strategies."""
import hashlib
import json
from pathlib import Path
from decimal import Decimal as D
from zipfile import ZipFile
from lxml import etree

ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'formula_lab/data'

def digest(b): return hashlib.sha256(b).hexdigest()
def variable(key,label,unit,lo=None,hi=None,exclusive=False):
    return dict(key=key,label=label,unit=unit,min=lo,max=hi,exclusive_min=exclusive)

def check_approval(card):
    # This manifest is deliberately NOT generated by build(). A source/formula
    # change requires a new documented review before its fingerprint is accepted.
    approvals=json.loads((OUT/'review_approvals.json').read_text())
    if approvals.get(card['id']) != card['fingerprint']:
        raise ValueError('Source/formula changed: document a new technical review before updating approvals: '+card['id'])

def build():
    report=json.loads((ROOT/'build/spike_a/extraction_report.json').read_text())
    inventory=[]
    for f in sorted((ROOT/'TC_DL').glob('*.docx')):
        with ZipFile(f) as z:
            xml=z.read('word/document.xml')
            doc=etree.fromstring(xml)
            ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main','m':'http://schemas.openxmlformats.org/officeDocument/2006/math'}
            raw=[''.join(p.xpath('.//w:t/text() | .//m:t/text()',namespaces=ns)) for p in doc.findall('.//w:p',ns)]
        inventory.append({'file':f.name,'sha256':digest(f.read_bytes()),'xml_sha256':digest(xml),'paragraphs':raw})
    (OUT/'docx_inventory.json').write_text(json.dumps(inventory,ensure_ascii=False,indent=2))
    definitions=[
        ('valve','Sai số áp suất chỉnh đặt van an toàn','QTKD_1.061_2021_ND_V2','QTKD 1.061 2021 ND V2.docx',245,264,['F001'],
         [variable('pm','Áp suất mở van','Pa',0),variable('pcd','Áp suất chỉnh đặt','Pa',0,exclusive=True)],'pm-pcd','Pa',[],{'pm':'103000','pcd':'100000'}),
        ('volume','Dung tích làm việc bình phân ly','QTKD_1.063_2021_BPL','QTKD 1.063 2021 BPL.docx',160,185,['F001'],
         [variable('vd','Nước còn lại trong ống đong 500 mL','mL',0,500)],'500-vd','mL',['initial'],{'vd':'125'}),
        ('rotation','Hiệu chỉnh thời gian quay tự do pít tông H3000','QTKD_1.071_2022_FINAL','QTKD 1.071 2022 FINAL.docx',244,282,['F002'],
         [variable('tau_t','Thời gian ở nhiệt độ t','s',0),variable('eta_t','Độ nhớt tại t','Pa.s',0,exclusive=True),variable('eta','Độ nhớt tiêu chuẩn','Pa.s',0,exclusive=True),variable('dt','Độ lớn chênh nhiệt độ','delta_degC',3,exclusive=True)],'tau_t*eta_t/eta','s',['rotation_conditions'],{'tau_t':'200','eta_t':'0.8','eta':'1','dt':'4'}),
        ('fall','Hiệu chỉnh tốc độ hạ pít tông H3000','QTKD_1.071_2022_FINAL','QTKD 1.071 2022 FINAL.docx',288,317,['F008'],
         [variable('vt','Tốc độ trung bình ba lần đo tại t','mm/min',0),variable('eta_t','Độ nhớt tại t','Pa.s',0,exclusive=True),variable('eta','Độ nhớt tiêu chuẩn','Pa.s',0,exclusive=True),variable('dt','Độ lớn chênh nhiệt độ','delta_degC',2,exclusive=True)],'vt*eta_t/eta','mm/min',['three_readings','fall_conditions'],{'vt':'2','eta_t':'0.8','eta':'1','dt':'3'}),
        ('gravity','Hiệu chỉnh áp suất theo gia tốc trọng trường H3000','QTKD_1.071_2022_FINAL','QTKD 1.071 2022 FINAL.docx',359,383,['F027'],
         [variable('p0','Tổng áp suất khắc độ','bar',0,exclusive=True),variable('gd','Gia tốc tại nơi đo','m/s2',0,exclusive=True),variable('g0','Gia tốc khi khắc độ','m/s2',0,exclusive=True)],'p0*gd/g0','bar',['different_gravity'],{'p0':'100','gd':'9.8','g0':'10'}),
        ('error','Sai số tương đối H3000 từ hai lần đo','QTKD_1.071_2022_FINAL','QTKD 1.071 2022 FINAL.docx',341,391,['F013','F014','F015','F033'],
         [variable('p','Áp suất danh nghĩa đã hiệu chỉnh trọng trường','bar',0,exclusive=True),variable('pc1','Chỉ thị chuẩn lần 1','bar',0),variable('pc2','Chỉ thị chuẩn lần 2','bar',0)],'((p-pc1)+(p-pc2))/2/p*100','%',['pressure_corrected'],{'p':'100','pc1':'99','pc2':'98'}),
    ]
    cards=[]; registry={}
    for id,title,stem,file,start,end,fids,variables,expr,unit,conditions,base in definitions:
        md=(ROOT/'build/spike_a'/f'{stem}.md').read_text().splitlines()
        entry=next(f for f in report['files'] if f['file']==file)
        formulas=[x for x in entry['formula_detail'] if x['fid'] in fids]
        source=next(x for x in inventory if x['file']==file)
        card=dict(id=id,title=title,file=file,stem=stem,section=formulas[0]['section'],
                  docx_sha256=source['sha256'],context='\n'.join(md[start-1:end]),
                  formulas=[dict(fid=x['fid'],latex=x['latex'],kind=x['kind']) for x in formulas],
                  revision='1',source_status='technical-reviewed',review_evidence='formula_lab/reports/source-review/REVIEW.md')
        card['fingerprint']=digest(json.dumps(card,sort_keys=True,ensure_ascii=False).encode())
        check_approval(card)
        cards.append(card)
        registry[id]=dict(id=id,title=title,variables=variables,expression=expr,unit=unit,conditions=conditions,
                          source_fingerprint=card['fingerprint'],revision='1')
    (OUT/'sources.json').write_text(json.dumps(cards,ensure_ascii=False,indent=2))
    (OUT/'registry.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2))
    # Oracle uses independent Decimal functions, never the executable expression strings.
    def oracle(id,v):
        x={k:D(str(w)) for k,w in v.items()}
        if id=='valve': return x['pm']-x['pcd']
        if id=='volume': return D(500)-x['vd']
        if id=='rotation': return (x['eta_t']/x['eta'])*x['tau_t']
        if id=='fall': return (x['eta_t']/x['eta'])*x['vt']
        if id=='gravity': return (x['gd']/x['g0'])*x['p0']
        return (D(1)-(x['pc1']+x['pc2'])/(D(2)*x['p']))*D(100)
    cases=[]
    # Twenty cases per group, development and held-out interleaved, same formula coverage.
    for group in ['selection','valid','input','boundary','source','ui']:
        for i in range(20):
            row=definitions[i%6]; id,title,_,_,_,_,_,variables,_,unit,conditions,base=row
            vals=dict(base)
            # Unseen numeric cases in holdout, no strategy reads this file.
            first=variables[0]['key']; vals[first]=str(D(vals[first])+D(i))
            for key in vals:
                if key != first: vals[key]=str(D(vals[key])+D(i)/D(100))
            inputs={k:{'value':v,'unit':next(x['unit'] for x in variables if x['key']==k)} for k,v in vals.items()}
            uc=dict(id=f'{group}-{i+1:02}',split='dev' if i<10 else 'holdout',group=group,
                    formula=id,question=f'Công thức {title.lower()} là gì?',inputs=inputs,
                    confirmations={c:True for c in conditions},expect='ok',unit=unit,
                    result=str(oracle(id,vals)),tolerance='0.00000001',severity='normal')
            if group=='selection':
                if i%5==0: uc.update(question='Công thức sai số là gì?',expect='clarify',formula=None)
                elif i%5==1: uc['question']=f'Tôi cần nhập số liệu để tính {title.lower()} theo quy trình.'
                elif i%5==2: uc['question']=f'Giải thích {title.lower()} và cho tôi công thức để nhập số.'
            elif group=='valid':
                if i%3==0:
                    u=inputs[first]['unit']
                    conversions={'Pa':('kPa',D(1000)),'bar':('kPa',D('0.01')),'mL':('L',D(1000)),'s':('min',D(60)),'mm/min':('mm/s',D(60))}
                    if u in conversions:
                        new,factor=conversions[u]; inputs[first]={'value':str(D(vals[first])/factor),'unit':new}
            elif group=='input':
                uc.update(expect='invalid',severity='critical')
                kind=i%5
                if kind==0: del inputs[first]
                elif kind==1: inputs[first]['value']=''
                elif kind==2: inputs[first]['value']='1,234'
                elif kind==3: inputs[first]['unit']='kg'
                else: inputs[first]['value']='NaN'
            elif group=='boundary':
                uc.update(expect='invalid',severity='critical')
                if i%2==0:
                    target=next((v for v in variables if v['exclusive_min']),variables[0])
                    inputs[target['key']]['value']=str(target['min']) if target['exclusive_min'] else '-1'
                elif conditions: uc['confirmations']={}
                else: inputs[first]['value']='Infinity'
            elif group=='source':
                uc.update(expect='blocked',severity='critical',mutation=['operator','missing_definition','version','wrong_source','missing_formula'][i%5])
            elif group=='ui':
                uc['ui_action']=['edit_invalidates','late_response','restore','source_binding','revision'][i%5]
            cases.append(uc)
    (OUT/'ucs.json').write_text(json.dumps(cases,ensure_ascii=False,indent=2))
    print(json.dumps({'docx':len(inventory),'calculators':len(cards),'ucs':len(cases)}))
if __name__=='__main__': build()
